### ISSUE TITLE
Tabs 

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/plenti#1]
Hi @jimafisk

I have been looking at this [article ](https://linguinecode.com/post/svelte-tabs-component) on tabs to see if I can adapt it. However, this particular tab component isn't for the showcase of Plenti's features as I mentioned in this issue: https://github.com/jamestagal/plenti-educenter/issues/3 but rather tabs in the ```hero``` section for installation.  

I thought it might be nice to have a small **Get Started with Plenti** section using tabs with the installation steps.
So I modified the example from that article and I got rid of the ```onMount``` import and function and incorporated the other code into the ```tabs-install.svelte``` [file](https://github.com/jamestagal/plenti/blob/main/layouts/components/tabs-install.svelte). 
At present I get the following error message ;
```terminal
❯ plenti serve
█████▒▒▒▒▒ Building... 2022/10/09 23:44:42 build.go:148: 
Error in Client build step
Could not get all layouts Could not add SSR Component for layouts/components/tabs-install.svelte: SyntaxError: Unexpected token '-' /home/runner/work/plenti/plenti/cmd/build/compile.go on line 274

 /home/runner/work/plenti/plenti/cmd/build/client.go on line 260

```

But the main thing I am unsure of is how to access the strings of each  ```label``` of the ```tabItems``` array into the template? I think the way I have it now is wrong but I not sure how to make it work! 😊 

```javascript
  // List of tab items with labels and values.
  let tabItems = [
    { label: "Homebrew (Mac)", value: 1 },
    { label: "Snap (Linux)", value: 2 },
    { label: "Scoop (Windows)", value: 3 },
    { label: "Manual", value: 4 }
  ];
```
Further down in the template
```javascript
    <ul class="tabs-header">
      <li class="default-tab">{tabItems.label.value(1)("")}</li>
      <li>{tabItems.label.value(2)("")}</li>
      <li>{tabItems.label.value(3)("")}</li>
      <li>{tabItems.label.value(4)("")}</li>
    </ul>
```
Let me know if this one is a quick fix! 
I keep on trying! 😄 
Ben

**Comment by jimafisk** [comment]
Hi @jamestagal,

Can you try renaming `tabs-install.svelte` to `tabs_install.svelte` or `tabsInstall.svelte`? I think it might be having trouble with hyphenated filenames. 

Given the `tabItems` array you specified, you could access `label` like `{tabItems[0].label}` and `value` like `{tabItems[0].value}` to get the first item in the array. Or you could loop through it like:

```svelte
<ul class="tabs-header">
  {#each tabItems as item}
    <li class="default-tab">{item.label}: {item.value}</li>
  {/each}
</ul>
```

Hope that helps!

**Comment by jamestagal** [comment]
Hi @jimafisk 
Thanks Jim. That fixed the errors and displays all the tab items on the page however the functionality isn't working yet!
I see an empty ```<ul></ul>``` above the component that might be the cause of this. I think it is coming from the following code in ```tabsInstall.svelte```.

```javascript
<ul>
{#if Array.isArray(items)}
  {#each items as item}
    <li class={activeTabValue === item.value ? 'active' : ''}>
      <span on:click={handleClick(item.value)}>{item.label}</span>
    </li>
  {/each}
{/if}
</ul>

```
This might need to be incorporated into the main tabs ```<ul>``` for it to work? because this is listening for the click event. If so, how could I combine them?

Ben

**Comment by jimafisk** [comment]
Hi @jamestagal I have a fix for this, can you give me permissions to push to this repo? Thanks!

**Comment by jimafisk** [comment]
Thanks @jamestagal, just pushed the code. Essentially I removed some things that didn't seem like they were being used and just made sure we were checking the variable that was being set by the click event (it looked like we were previously checking a variable that was never getting set). Let me know if any of that is unclear! Thanks!

**Comment by jamestagal** [comment]
Great thanks Jim.

I see where you have removed the unnecessary code and incorporated the ```click``` event into the ```tabs``` div. 
Thank you. I just need to work on its styling now. 😄 

Thanks again.

**Comment by jamestagal** [comment]
Also I am not sure if that tabs component positioned where I have it, makes it too cluttered! What do you think?
It could go in its own section below perhaps?
Ben

**Comment by jimafisk** [comment]
Yeah it's a cool idea, but it might make the header section a little too busy. Might be worth trying to put it in a separate section and seeing how that looks!
